[server]
port =
max_connections =

[database]
host = " "
user = " "
password = " "

# Protocolo para recibir datos del formulario
[protocol]
delimiter = ";"
format = "PlainText"

[[database.tables]]
name = " "
fields = ["id", "nombre", "matricula"]
