[server]
port= 0
max_connections = 0

[database]
host = " "
user = " "
password = " "

# Proocolo que indica como se van a mandar los datos
[protocol]
delimiter = ";"
format = "PlainText"

[[database.tables]]
name = "Nombre_de_tabla"
fields = ["id", "nombre", "matricula"]
